#!/usr/bin/env python
from Bio import SeqIO
for record in SeqIO.parse("/hwfssz1/ST_EARTH/P18Z10200N0160/P18Z10200N0197_temp/fuyiyang/exercise/document/human_mitochondrial.fasta", "fasta"):
    #01
    print("seq_len:", len(record.seq))
    print("gc_proportion:", (record.seq.count("C") + record.seq.count("G")) / len(record.seq))
